/**
 * Created by lvxianlei on 2017/4/25.
 */
exports.API = {
    LOGIN: 'LOGIN', ////登录
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',//登录成功
    LOGIN_ERROR: 'LOGIN_ERROR',//登录失败
    LOGOUT: 'LOGOUT',//退出

    GET_NODE_LIST: 'GET_NODE_LIST', //pending , success, failure
    GET_NODE_LIST_ERROR: 'GET_NODE_LIST_ERROR',
    GET_NODE_LIST_SUCCESS: 'GET_NODE_LIST_SUCCESS',
    GET_ALL_NODE_LIST: 'GET_ALL_NODE_LIST',
    GET_ALL_NODE_LIST_ERROR: 'GET_ALL_NODE_LIST_ERROR',
    GET_ALL_NODE_LIST_SUCCESS: 'GET_ALL_NODE_LIST_SUCCESS',

    GET_PRODUCT_LIST: 'GET_PRODUCT_LIST', 
    GET_PRODUCT_LIST_ERROR: 'GET_PRODUCT_LIST_ERROR',
    GET_PRODUCT_LIST_SUCCESS: 'GET_PRODUCT_LIST_SUCCESS',

    CONVEY_FLAG: 'CONVEY_FLAG',//获取application组件的flag对象
    
    GET_DESIGN_ID: 'GET_DESIGN_ID',//获取用户的DesignId
    GET_DESIGN_ID_SUCCESS: 'GET_DESIGN_ID_SUCCESS',//获取用户DesignID失败
    GET_DESIGN_ID_ERROR: 'GET_DESIGN_ID_ERROR',//获取用户DesignID失败

    DESIGN_ID_GET_START: 'DESIGN_ID_GET_START',//开始获取用户的DesignId,判断页面展示内容
    DESIGN_ID_GET_SUCCESS: 'DESIGN_ID_GET_SUCCESS',//成功获取用户的DesignId
    DESIGN_ID_GET_ERROR: 'DESIGN_ID_GET_ERROR',//获取用户DesignID失败

    NODE_LIST_GET_START: 'NODE_LIST_GET_START',//开始获取所有阶段子项品类列表
    NODE_LIST_GET_SUCCESS: 'NODE_LIST_GET_SUCCESS',//获取所有阶段子项品类列表
    NODE_LIST_GET_ERROR: 'NODE_LIST_GET_ERROR',//获取所有阶段子项品类列表失败

    SHAPE_LIST_GET_START: 'SHAPE_LIST_GET_START',//开始获取模型信息
    SHAPE_LIST_GET_SUCCESS: 'SHAPE_LIST_GET_SUCCESS',//获取模型信息成功
    SHAPE_LIST_GET_ERROR: 'SHAPE_LIST_GET_ERROR',//获取模型信息失败

    DESIGN_SHAPE_CHOOSE: 'DESIGN_SHAPE_CHOOSE',//选取用户某个工程

    SHAPE_LIST_UPDATE_START: 'SHAPE_LIST_UPDATE_START',//开始修改某个模型信息
    SHAPE_LIST_UPDATE: 'SHAPE_LIST_UPDATE',//修改某个模型信息
    SHAPE_LIST_UPDATE_ERROR: 'SHAPE_LIST_UPDATE_ERROR',//修改模型信息失败

    MODEL_ITEM_START: 'MODEL_ITEM_START',//开始拉取模型
    MODEL_ITEM: 'MODEL_ITEM',//拉取模型
    MODEL_ITEM_ERROR: 'MODEL_ITEM_ERROR',//拉取模型失败

};